### ISSUE TITLE
Chestplate still visible to other players after removing the armored elytra

### ISSUE THREAD

**Issue by ghost** [mrmelon54/armored_elytra#11]
chestplate still visible to other players after taking the armored elytra off

**Comment by mrmelon54** [comment]
I think this is fixed

**Comment by oathompsonjones** [comment]
This is not fixed on 1.20.1

**Comment by CoalSephos** [comment]
issue is still happening on version 1.20.1, will you be providing backporting support or continuing to only update 1.20.4
